Update ko-builder.yml

diff --git a/.github/workflows/ko-builder.yml b/.github/workflows/ko-builder.yml
--- a/.github/workflows/ko-builder.yml
+++ b/.github/workflows/ko-builder.yml
@@ -41,13 +41,48 @@ on:
 
 
 jobs:
+  detect-env:
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write # Needed to detect the current reusable repository and ref.
+      contents: read
+    outputs:
+      builder_repo: ${{ steps.detect.outputs.builder_repo }}
+      builder_ref: ${{ steps.detect.outputs.builder_ref }}
+    steps:
+      - name: Detect the builder ref
+        id: detect
+        shell: bash
+        run: | 
+          status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=slsa-framework/slsa-github-generator-go/builder" -o jwt.json -w '%{http_code}')
+          if [[ $status_code -ge 400 ]]; then
+              error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
+              echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
+              exit 1;
+          fi
+          export WORKFLOW_REF=$(cat jwt.json | jq -r '.value' | cut -d "." -f2 | base64 -d | jq -r '.job_workflow_ref')
+          if [ -z $WORKFLOW_REF ]; then
+            echo "OIDC token parsing failure: job_workflow_ref could not be retrieved"
+            exit 1;
+          fi
+          echo "::set-output name=builder_repo::$(echo $WORKFLOW_REF | cut -d "@" -f1 | cut -d '/' -f1-2)"
+          echo "::set-output name=builder_ref::$(echo $WORKFLOW_REF | cut -d "@" -f2)"
+          
   build-builder:
     runs-on: ubuntu-latest
+    needs: detect-env
     permissions:
       contents: read
     outputs:
       builder-sha256: ${{ steps.build-builder.outputs.sha256 }}
     steps:
+      - name: Checkout the repository
+        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
+        with:
+          fetch-depth: 0
+          repository: "${{ needs.detect-env.outputs.builder_repo }}"
+          ref: "${{ needs.detect-env.outputs.builder_ref }}"
+  
       - name: Build builder
         id: build-builder
         run: |
@@ -55,6 +90,12 @@ jobs:
           
           echo "building the builder"
           echo "::set-output name=builder-sha256::abcedfg"
+          
+      - name: Upload builder
+        run: |
+          set -euo pipefail
+          
+          echo "TODO: upload builder"
       
   build-dry:
     runs-on: ubuntu-latest
