Update ko.yml

diff --git a/.github/workflows/ko.yml b/.github/workflows/ko.yml
--- a/.github/workflows/ko.yml
+++ b/.github/workflows/ko.yml
@@ -141,16 +141,16 @@ jobs:
       # We may be able to have a generic provenance uploader, but for now let's seperate to keep things simple.
       #TODO: can pull a static image and verify provenance
         
-      - name: Fetch OIDC token
-        run: |
-          set -euo pipefail
+#       - name: Fetch OIDC token
+#         run: |
+#           set -euo pipefail
           
-          status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" -o jwt.json -w '%{http_code}')
-          if [[ $status_code -ge 400 ]]; then
-              error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
-              echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
-              exit 1;
-          fi
+#           status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" -o jwt.json -w '%{http_code}')
+#           if [[ $status_code -ge 400 ]]; then
+#               error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
+#               echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
+#               exit 1;
+#           fi
 
        # TODO: downlaoading and pinning the download instead
       # remko/dsadmin/blob/7a6939179bc56b1be28cada040f2b4a148e3e14a/.github/workflows/publish-release.yml
