Update ko.yml

diff --git a/.github/workflows/ko.yml b/.github/workflows/ko.yml
--- a/.github/workflows/ko.yml
+++ b/.github/workflows/ko.yml
@@ -191,16 +191,22 @@ jobs:
           # "ghcr.io/laurentsimon/slsa-on-github-test/helloworld" appears to be a private repository, please confirm uploading to the transparency log at "https://rekor.sigstore.dev" [Y/N]: 
           # WARNING: skipping transparency log upload (use --force to upload from scripts)
           
-          # --oidc-client-secret-file
+          export JWT=$(cat jwt.json | jq -r '.value')
+          if [ -z $JWT ]; then
+            echo "OIDC token parsing failure: value could not be retrieved"
+            exit 1;
+          fi
+          
+          # --oidc-client-secret-file jwt.json
           echo cosign attest --predicate "$UNTRUSTED_PREDICATE_FILE" \
             --type "slsaprovenance" \
-            --identity-token "$(cat jwt.json)" \
+            --identity-token "$JWT" \
             --force \
             "$UNTRUSTED_CONTAINER_IMAGE"
             
           COSIGN_EXPERIMENTAL=1 cosign attest --predicate "$UNTRUSTED_PREDICATE_FILE" \
             --type "slsaprovenance" \
-            --identity-token "$(cat jwt.json)" \
+            --identity-token "$JWT" \
             "$UNTRUSTED_CONTAINER_IMAGE"
 
           
