Update run-error.yml

diff --git a/.github/workflows/run-error.yml b/.github/workflows/run-error.yml
--- a/.github/workflows/run-error.yml
+++ b/.github/workflows/run-error.yml
@@ -29,7 +29,7 @@ jobs:
         run: |
           echo "CONTINUE: $CONTINUE"
           echo "SUCCESS: $SUCCESS"
-          [ "$CONTINUE" == "false" ] && [ "$SUCCESS" == "false" ] && echo "caught error" && exit 1
+          [ "$CONTINUE" == "false" ] && [ "$SUCCESS" == "false" ] && echo "caught error" && exit 20
         #run: echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
           
 #   run-job2:
