Update run-error.yml

diff --git a/.github/workflows/run-error.yml b/.github/workflows/run-error.yml
--- a/.github/workflows/run-error.yml
+++ b/.github/workflows/run-error.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  run-job:
+  run-job1:
     outputs:
       outcome: ${{ steps.final.outputs.outcome }}
     runs-on: ubuntu-latest
@@ -20,16 +20,7 @@ jobs:
         env:
           STEPS_CONTEXT: ${{ toJson(steps) }}
           SUCCESS: ${{ steps.step1.outcome != 'failure' && steps.step2.outcome != 'failure' }}
-        run: |
-          echo "$STEPS_CONTEXT"
-          echo "$OUTCOME"
-          if [[ "$SUCCESS" == "true" ]]; then
-             echo success
-             echo "outcome=success" >> $GITHUB_OUTPUT
-          else
-            echo failure
-            echo "outcome=failure" >> $GITHUB_OUTPUT
-          fi
+        run: echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
           
   run-job2:
     outputs:
@@ -48,22 +39,13 @@ jobs:
         env:
           STEPS_CONTEXT: ${{ toJson(steps) }}
           SUCCESS: ${{ steps.step1.outcome != 'failure' && steps.step2.outcome != 'failure' }}
-        run: |
-          echo "$STEPS_CONTEXT"
-          echo "$OUTCOME"
-          if [[ "$SUCCESS" == "true" ]]; then
-             echo success
-             echo "outcome=success" >> $GITHUB_OUTPUT
-          else
-            echo failure
-            echo "outcome=failure" >> $GITHUB_OUTPUT
-          fi
+        run: echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> $GITHUB_OUTPUT
 
   verify:
     name: verif
-    needs: [run-job]
+    needs: [run-job1, run-job2]
     runs-on: ubuntu-latest
     steps:
       - env:
-          OUTCOME: ${{ needs.run-job.outputs.outcome }}
-        run: echo "outcome=$OUTCOME"
+          SUCCESS: ${{ needs.run-job1.outcome != 'failure' && steps.run-job2.outcome != 'failure' }}
+        run: echo "outcome=$SUCCESS"
